version = 1

test_patterns = [
    "tests-karma/**",
    "tests-nose/**"
]

exclude_patterns = ["plugins/**"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"